'use strict';
const c=document.getElementById('game'),ctx=c.getContext('2d');
const W=1280,H=720;let sx=1,sy=1;function resize(){c.width=W*devicePixelRatio;c.height=H*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);sx=c.clientWidth/W;sy=c.clientHeight/H}addEventListener('resize',resize);resize();
const saveKey='arashiFabricioSave';let save=JSON.parse(localStorage.getItem(saveKey)||'null')||{unlocked:1,coins:0,skills:{dash:0,health:0,shuriken:0},romance:true,stage:1};function persist(){localStorage.setItem(saveKey,JSON.stringify(save))}
const input={left:false,right:false,jump:false,attack:false,shuriken:false,dash:false};
addEventListener('keydown',e=>{const m={ArrowLeft:'left',a:'left',ArrowRight:'right',d:'right',ArrowUp:'jump',w:'jump',' ':'jump',j:'attack',k:'shuriken',l:'dash'};if(m[e.key]){input[m[e.key]]=true;e.preventDefault()}if(e.key==='Escape')togglePause()});addEventListener('keyup',e=>{const m={ArrowLeft:'left',a:'left',ArrowRight:'right',d:'right',ArrowUp:'jump',w:'jump',' ':'jump',j:'attack',k:'shuriken',l:'dash'};if(m[e.key])input[m[e.key]]=false});document.querySelectorAll('[data-key]').forEach(b=>{let k=b.dataset.key;b.onpointerdown=e=>{input[k]=true;e.preventDefault()};b.onpointerup=b.onpointercancel=b.onpointerleave=e=>{input[k]=false}});
const menu=document.getElementById('menu'),panel=document.getElementById('panel'),hud=document.getElementById('hud'),touch=document.getElementById('touch');let running=false,paused=false,stage=1,world,player,particles=[],last=0;
function showPanel(html){panel.innerHTML='<div class="panel-inner">'+html+'</div>';panel.classList.remove('hidden');menu.classList.add('hidden');hud.classList.add('hidden');touch.classList.add('hidden')}
function closePanel(){panel.classList.add('hidden');menu.classList.remove('hidden')}
document.getElementById('settingsBtn').onclick=()=>showPanel(`<h2>Configurações</h2><div class="row"><span>Efeitos românticos</span><label class="toggle"><input id="rom" type="checkbox" ${save.romance?'checked':''}> ❤️</label></div><p class="story">Os efeitos românticos adicionam partículas de coração e brilhos em momentos especiais. Eles não alteram a dificuldade.</p><button class="close" onclick="closePanel()">VOLTAR</button>`);
document.getElementById('skillsBtn').onclick=skillsMenu;document.getElementById('stagesBtn').onclick=stagesMenu;document.getElementById('playBtn').onclick=()=>startStage(save.stage||1);
function stagesMenu(){let cards='';for(let i=1;i<=80;i++){let locked=i>save.unlocked;let boss=i%20===0;cards+=`<button class="stage-card ${locked?'locked':''} ${boss?'boss':''}" ${locked?'disabled':''} onclick="startStage(${i})"><strong>FASE ${i}</strong><span>${boss?'👹 CHEFE':'★ ★ ★'}</span></button>`}showPanel(`<h2>Seleção de fases</h2><div class="grid">${cards}</div><button class="close" onclick="closePanel()">VOLTAR</button>`)}
function skillsMenu(){let s=save.skills;showPanel(`<h2>Habilidades</h2><p>Moedas: <b>● ${save.coins}</b></p>${skillCard('dash','Dash','Reduz o tempo de recarga.',s.dash,5,30)}${skillCard('health','Vitalidade','Aumenta a vida máxima.',s.health,4,45)}${skillCard('shuriken','Shuriken','Aumenta dano do arremesso.',s.shuriken,5,35)}<button class="close" onclick="closePanel()">VOLTAR</button>`)}
function skillCard(id,name,desc,lv,max,cost){let price=cost*(lv+1);return `<div class="skill-card"><div class="row"><strong>${name} Lv.${lv}/${max}</strong><span>● ${price}</span></div><div class="muted">${desc}</div><button ${lv>=max||save.coins<price?'disabled':''} onclick="buySkill('${id}',${price})">${lv>=max?'MÁXIMO':'MELHORAR'}</button></div>`}
window.buySkill=(id,cost)=>{if(save.coins>=cost&&save.skills[id]<5){save.coins-=cost;save.skills[id]++;persist();skillsMenu()}};window.closePanel=closePanel;window.startStage=startStage;
function makeStage(n){let biome=n<=20?'gelo':n<=40?'floresta':n<=60?'ruinas':'fortaleza';let boss=n%20===0;let plats=[];let hazards=[];let enemies=[];let x=0;const len=4300+(n%5)*300;plats.push({x:0,y:600,w:900,h:120});for(let i=1;i<18+(n%5);i++){let gap=120+((i*37+n*19)%130),w=170+((i*53+n*7)%180),y=390+((i*71+n*13)%170);x+=gap;plats.push({x,y,w,h:60});if(i%3===0)hazards.push({x:x+w*.35,y:y-22,w:55,h:22,type:i%2?'spike':'blade'});if(i%4===0)enemies.push({x:x+w*.65,y:y-52,type:i%7===0?'ranged':'melee',dir:-1,alive:true});}
plats.push({x:x+250,y:520,w:700,h:100});if(boss)enemies.push({x:x+500,y:455,type:'boss',dir:-1,alive:true,boss:true,hp:18});else hazards.push({x:x+400,y:498,w:60,h:22,type:'spike'});return {n,biome,boss,len,plats,hazards,enemies,checkpoints:[900,2400],goal:x+700};}
function startStage(n){stage=n;world=makeStage(n);player={x:80,y:500,w:34,h:68,vx:0,vy:0,onGround:false,jumps:2,facing:1,hp:3+save.skills.health,maxhp:3+save.skills.health,inv:0,dash:0,attack:0,shuriken:0,disguise:0,checkpoint:80};particles=[];running=true;paused=false;menu.classList.add('hidden');panel.classList.add('hidden');hud.classList.remove('hidden');touch.classList.remove('hidden');document.getElementById('stageLabel').textContent=`FASE ${n}${world.boss?' • CHEFE':''}`;updateHud()}
function updateHud(){document.getElementById('coinLabel').textContent='● '+save.coins;document.getElementById('hpLabel').textContent='♥'.repeat(Math.max(0,player?.hp||0))}
function togglePause(){if(!running)return;paused=!paused;if(paused)showPause();else{panel.classList.add('hidden');hud.classList.remove('hidden');touch.classList.remove('hidden')}}
function showPause(){showPanel(`<h2>${world.boss?'Batalha':'Pausa'}</h2><p class="story">Arashi Fabricio atravessa ${world.biome==='gelo'?'as terras congeladas':world.biome==='floresta'?'a floresta sombria':world.biome==='ruinas'?'as ruínas esquecidas':'a fortaleza das sombras'}.</p><button onclick="togglePause()">CONTINUAR</button><button onclick="quitGame()">SAIR DA FASE</button>`)}window.togglePause=togglePause;window.quitGame=()=>{running=false;paused=false;menu.classList.remove('hidden');panel.classList.add('hidden');hud.classList.add('hidden');touch.classList.add('hidden')};document.getElementById('pauseBtn').onclick=togglePause;
function rectHit(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y}function groundAt(px,py){let best=null;for(const p of world.plats){if(px>p.x-10&&px<p.x+p.w+10&&py<=p.y+10&&py>=p.y-90){if(!best||p.y<best.y)best=p}}return best}
function hurt(){if(player.inv>0)return;player.hp--;player.inv=1.1;burst(player.x+15,player.y+30,'hit');if(player.hp<=0){player.hp=player.maxhp;player.x=player.checkpoint;player.y=400;player.vy=0;burst(player.x,player.y,'respawn')}updateHud()}
function attack(){if(player.attack<=0){player.attack=.28;burst(player.x+player.facing*35,player.y+25,'slash');for(const e of world.enemies){if(e.alive&&Math.abs(e.x-player.x)<80&&Math.abs(e.y-player.y)<90){e.hp=(e.hp||2)-1;if(e.hp<=0){e.alive=false;save.coins+=5;burst(e.x,e.y,'coin')}}}}}
function shuriken(){if(player.shuriken<=0){player.shuriken=.22;world.projectiles??=[];world.projectiles.push({x:player.x+player.facing*30,y:player.y+25,vx:player.facing*760,life:1.2})}}
function dash(){if(player.dash<=0){player.dash=.8-Math.min(.3,save.skills.dash*.05);player.vx=player.facing*900;burst(player.x,player.y,'dash')}}
function update(dt){if(!running||paused)return;dt=Math.min(dt,.033);player.inv=Math.max(0,player.inv-dt);player.attack=Math.max(0,player.attack-dt);player.shuriken=Math.max(0,player.shuriken-dt);player.dash=Math.max(0,player.dash-dt);let dir=(input.right?1:0)-(input.left?1:0);if(dir){player.facing=dir;player.vx+=dir*260*dt;player.vx=Math.max(-230,Math.min(230,player.vx))}else player.vx*=Math.pow(.001,dt);if(input.dash){dash();input.dash=false}if(input.attack){attack();input.attack=false}if(input.shuriken){shuriken();input.shuriken=false}if(input.jump){if(player.jumps>0){player.vy=-610;player.jumps--;player.onGround=false;burst(player.x+15,player.y+60,'jump')}input.jump=false}
player.vy+=1550*dt;let nx=player.x+player.vx*dt,ny=player.y+player.vy*dt;let prevY=player.y;player.x=nx;player.y=ny;player.onGround=false;for(const p of world.plats){if(player.x+player.w>p.x&&player.x<p.x+p.w&&prevY+player.h<=p.y&&player.y+player.h>=p.y&&player.vy>=0){player.y=p.y-player.h;player.vy=0;player.onGround=true;player.jumps=2}}if(player.y>820){hurt();player.x=player.checkpoint;player.y=350;player.vy=0}for(const h of world.hazards){if(rectHit(player,h))hurt()}for(const e of world.enemies){if(!e.alive)continue;if(e.boss){e.x+=Math.sin(performance.now()/600)*40*dt;e.y=450;if(Math.abs(e.x-player.x)<130&&Math.random()<.02)hurt()}else{e.x+=e.dir*(e.type==='ranged'?25:45)*dt;if(Math.random()<.006)e.dir*=-1;if(rectHit(player,{x:e.x,y:e.y,w:34,h:55}))hurt()}}
for(const q of world.projectiles||[]){q.x+=q.vx*dt;q.life-=dt;if(q.life>0){for(const e of world.enemies){if(e.alive&&Math.abs(q.x-e.x)<40&&Math.abs(q.y-e.y)<55){e.hp=(e.hp||2)-(1+save.skills.shuriken);if(e.hp<=0){e.alive=false;save.coins+=5;burst(e.x,e.y,'coin')}q.life=0}}}}world.projectiles=(world.projectiles||[]).filter(q=>q.life>0);if(player.x>player.checkpoint+1000)player.checkpoint=player.x;if(player.x>world.goal){completeStage()}if(Math.random()<.12&&save.romance)burst(player.x+Math.random()*60,player.y-20,'heart');updateHud()}
function completeStage(){running=false;save.unlocked=Math.max(save.unlocked,Math.min(80,stage+1));save.stage=Math.min(80,stage+1);save.coins+=25;persist();hud.classList.add('hidden');touch.classList.add('hidden');showPanel(`<h2>${world.boss?'CHEFE DERROTADO':'FASE CONCLUÍDA'} ✦</h2><p style="text-align:center;font-size:42px">❤️ ✨ ❤️</p><p class="story">Você concluiu a fase ${stage}. Recompensa: <b>● 25 moedas</b>.</p><button onclick="startStage(${Math.min(80,stage+1)})">PRÓXIMA FASE</button><button onclick="stagesMenu()">SELECIONAR FASE</button><button onclick="quitGame()">MENU</button>`)}window.stagesMenu=stagesMenu;
function burst(x,y,type){let n=type==='heart'?2:8;for(let i=0;i<n;i++)particles.push({x,y,vx:(Math.random()-.5)*100,vy:(Math.random()-.8)*140,life:1,type})}
function draw(){ctx.clearRect(0,0,W,H);let cam=Math.max(0,Math.min(world?world.len-W:0,(player?.x||0)-W*.35));let colors={gelo:['#0b1624','#18304a','#b7d5e8'],floresta:['#08160f','#123b2b','#2f6b50'],ruinas:['#171019','#3a2835','#8b6478'],fortaleza:['#0b0b12','#252532','#655f7d']};let col=colors[world?.biome||'gelo'];ctx.fillStyle=col[0];ctx.fillRect(0,0,W,H);for(let i=0;i<14;i++){let bx=((i*270-cam*.12)%1800+1800)%1800;ctx.fillStyle=col[1];ctx.beginPath();ctx.moveTo(bx,560);ctx.lineTo(bx+100,350+(i%3)*40);ctx.lineTo(bx+230,560);ctx.fill()}if(world){for(const p of world.plats){ctx.fillStyle=col[2];ctx.fillRect(p.x-cam,p.y,p.w,p.h);ctx.fillStyle='rgba(0,0,0,.35)';ctx.fillRect(p.x-cam,p.y,p.w,8)}for(const h of world.hazards){ctx.fillStyle='#c73d4b';if(h.type==='spike'){for(let x=h.x;x<h.x+h.w;x+=14){ctx.beginPath();ctx.moveTo(x-cam,h.y+22);ctx.lineTo(x+7-cam,h.y-8);ctx.lineTo(x+14-cam,h.y+22);ctx.fill()}}else{ctx.fillRect(h.x-cam,h.y,h.w,h.h);ctx.fillStyle='#f07b7b';ctx.fillRect(h.x-cam,h.y,h.w,4)}}for(const e of world.enemies){if(!e.alive)continue;ctx.save();ctx.translate(e.x-cam,e.y);ctx.fillStyle=e.boss?'#b83d56':'#14171d';ctx.beginPath();ctx.arc(17,15,e.boss?24:17,0,Math.PI*2);ctx.fill();ctx.fillRect(4,30,26,e.boss?55:40);ctx.fillStyle='#ddd';ctx.fillRect(10,12,5,3);ctx.restore()}for(const q of world.projectiles||[]){ctx.fillStyle='#f3f5ff';ctx.fillRect(q.x-cam,q.y,16,3)}drawPlayer(cam);for(const p of particles){ctx.globalAlpha=Math.max(0,p.life);ctx.fillStyle=p.type==='heart'?'#ff7aa2':p.type==='coin'?'#ffd45a':'#dfe9ff';if(p.type==='heart'){ctx.font='18px serif';ctx.fillText('♥',p.x-cam,p.y)}else ctx.fillRect(p.x-cam,p.y,5,5);ctx.globalAlpha=1}particles.forEach(p=>{p.x+=p.vx*.016;p.y+=p.vy*.016;p.vy+=80*.016;p.life-=.016});particles=particles.filter(p=>p.life>0);if(running){ctx.fillStyle='rgba(255,255,255,.75)';ctx.font='16px system-ui';ctx.fillText(world.boss?'DERROTE O CHEFE':'CHEGUE AO FINAL',W-220,35)}}}
function drawPlayer(cam){if(!player)return;ctx.save();ctx.translate(player.x-cam,player.y);ctx.scale(player.facing,1);ctx.globalAlpha=player.inv>0&&Math.floor(player.inv*12)%2?0.35:1;ctx.fillStyle='#05070b';ctx.beginPath();ctx.arc(17,15,17,0,Math.PI*2);ctx.fill();ctx.fillRect(4,29,26,38);ctx.fillStyle='#dbe3ed';ctx.fillRect(17,12,8,3);ctx.fillStyle='#141b25';ctx.fillRect(-6,32,12,8);ctx.fillStyle='#0a0d13';ctx.fillRect(26,32,12,8);if(player.attack>0){ctx.strokeStyle='#e7eef8';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(24,35);ctx.lineTo(72,12);ctx.stroke()}ctx.restore()}
function loop(t){let dt=(t-last)/1000;last=t;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
