'use strict';
const canvas=document.getElementById('game'),ctx=canvas.getContext('2d');
const VW=1280,VH=720;let dpr=1;function resize(){dpr=Math.min(2,devicePixelRatio||1);canvas.width=VW*dpr;canvas.height=VH*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)}addEventListener('resize',resize);resize();
const KEY='arashiFabricio_v2';let save=JSON.parse(localStorage.getItem(KEY)||'null')||{stage:1,unlocked:1,coins:0,skills:{dash:0,health:0,shuriken:0,armor:0},artifacts:{heart:false,shadow:false},romance:true};const persist=()=>localStorage.setItem(KEY,JSON.stringify(save));
const input={left:false,right:false,jump:false,attack:false,shuriken:false,dash:false};const map={ArrowLeft:'left',a:'left',ArrowRight:'right',d:'right',ArrowUp:'jump',w:'jump',' ':'jump',j:'attack',k:'shuriken',l:'dash'};
addEventListener('keydown',e=>{if(map[e.key]){input[map[e.key]]=true;e.preventDefault()}if(e.key==='Escape')pause()});addEventListener('keyup',e=>{if(map[e.key])input[map[e.key]]=false});document.querySelectorAll('[data-key]').forEach(b=>{const k=b.dataset.key;b.onpointerdown=e=>{input[k]=true;e.preventDefault()};b.onpointerup=b.onpointercancel=b.onpointerleave=()=>input[k]=false});
const menu=document.getElementById('menu'),panel=document.getElementById('panel'),hud=document.getElementById('hud'),touch=document.getElementById('touch');let running=false,paused=false,world=null,p=null,cam=0,particles=[],last=0,shake=0;
const biomes=[['Gelo','gelo'],['Floresta','floresta'],['Pântano','pantano'],['Ruínas','ruinas'],['Fortaleza','fortaleza']];
function panelShow(html){panel.innerHTML='<div class="panelInner">'+html+'</div>';panel.classList.remove('hidden');menu.classList.add('hidden');hud.classList.add('hidden');touch.classList.add('hidden')}function panelClose(){panel.classList.add('hidden');menu.classList.remove('hidden')}
function stages(){let html='<h2>Mapa da jornada</h2><p class="story">Cinco regiões, 80 fases e uma curva de dificuldade gradual. Cada décima fase termina em uma arena de chefe.</p><div class="grid">';for(let i=1;i<=80;i++){const lock=i>save.unlocked,boss=i%10===0,act=Math.ceil(i/20);html+=`<button class="stageCard ${boss?'boss ':''}${lock?'locked':''}" ${lock?'disabled':''} onclick="start(${i})"><b>${i<10?'0':''}${i} · ATO ${act}</b><small>${boss?'👹 ARENA DE CHEFE':biomes[(act-1)%5][0]}</small></button>`}html+='</div><button class="close" onclick="panelClose()">VOLTAR</button>';panelShow(html)}
function skills(){const s=save.skills;const card=(id,n,desc,max,cost)=>{let lv=s[id],price=cost*(lv+1);return `<div class="skill"><div class="row"><b>${n} · Nv. ${lv}/${max}</b><span>◈ ${price}</span></div><p>${desc}</p><button ${lv>=max||save.coins<price?'disabled':''} onclick="buy('${id}',${price})">${lv>=max?'MÁXIMO':'MELHORAR'}</button></div>`};panelShow(`<h2>Árvore de habilidades</h2><p class="story">Moedas: ◈ ${save.coins}. Cada melhoria altera a jogabilidade.</p>${card('dash','Passo Sombrio','Reduz a recarga do dash.',5,25)}${card('health','Vigor','Aumenta a vida máxima.',4,35)}${card('shuriken','Lâmina Distante','Aumenta o dano dos shurikens.',5,30)}${card('armor','Manto','Reduz o dano recebido e amplia a invulnerabilidade.',3,55)}<button class="close" onclick="panelClose()">VOLTAR</button>`)}
function artifacts(){panelShow(`<h2>Artefatos</h2><p class="story">Relíquias opcionais que mudam o estilo da aventura.</p><div class="artifact"><div class="artifactIcon">♥</div><div><b>Coração de Lua</b><br><span class="muted">Ao vencer uma fase, há uma pequena chance de recuperar vida.</span></div><button onclick="toggleArtifact('heart')">${save.artifacts.heart?'EQUIPADO':'EQUIPAR'}</button></div><div class="artifact"><div class="artifactIcon">☾</div><div><b>Sombra Errante</b><br><span class="muted">Dash deixa uma sombra que causa dano ao tocar inimigos.</span></div><button onclick="toggleArtifact('shadow')">${save.artifacts.shadow?'EQUIPADO':'EQUIPAR'}</button></div><button class="close" onclick="panelClose()">VOLTAR</button>`)}
window.buy=(id,c)=>{if(save.coins>=c&&save.skills[id]<5){save.coins-=c;save.skills[id]++;persist();skills()}};window.toggleArtifact=id=>{save.artifacts[id]=!save.artifacts[id];persist();artifacts()};window.panelClose=panelClose;window.stages=stages;
document.getElementById('playBtn').onclick=()=>start(save.stage);document.getElementById('stagesBtn').onclick=stages;document.getElementById('skillsBtn').onclick=skills;document.getElementById('artifactsBtn').onclick=artifacts;document.getElementById('settingsBtn').onclick=()=>panelShow(`<h2>Configurações</h2><div class="row"><span>Efeitos românticos</span><label class="toggle"><input id="rom" type="checkbox" ${save.romance?'checked':''}> ♥</label></div><p class="story">Ativa partículas, brilhos e pequenas mensagens românticas. O efeito é cosmético e não altera a dificuldade.</p><button class="close" onclick="panelClose()">VOLTAR</button>`);panel.addEventListener('change',e=>{if(e.target.id==='rom'){save.romance=e.target.checked;persist()}});document.getElementById('pauseBtn').onclick=pause;
function seed(n){return (Math.sin(n*12.9898)*43758.5453)%1}
function makeLevel(n){const act=Math.ceil(n/20),boss=n%10===0,biome=biomes[(act-1)%biomes.length][1],difficulty=Math.min(5,1+Math.floor((n-1)/16));let parts=[],hazards=[],enemies=[],decor=[],x=0;const len=6200+(n%7)*340;parts.push({x:-200,y:610,w:1150,h:120});let i=0;while(x<len-1100){i++;let gap=90+Math.abs(seed(i+n))*100,w=150+Math.abs(seed(i*3+n))*230,y=420+Math.abs(seed(i*7+n))*150;x+=gap;parts.push({x,y,w,h:55+((i+n)%3)*10});const r=Math.abs(seed(i*9+n));if(r<.28)hazards.push({type:'spikes',x:x+w*.35,y:y-24,w:55,h:24});else if(r<.45)hazards.push({type:'saw',x:x+w*.65,y:y-28,w:30,h:30,phase:i});if(i%5===0)parts.push({x:x+w+35,y:y-90,w:120,h:35,moving:true,base:x+w+35,range:70,phase:i});if(i%4===0)enemies.push({type:i%6===0?'ranged':'melee',x:x+w*.55,y:y-58,hp:1+difficulty,dir:i%2?1:-1,patrol:80+30*difficulty});if(i%7===0)decor.push({type:'lantern',x:x+w*.2,y:y-80});}
parts.push({x:len-1000,y:560,w:1050,h:160});if(boss){enemies.push({type:'boss',x:len-450,y:470,hp:14+act*4,maxHp:14+act*4,dir:-1,phase:0})}else{hazards.push({type:'spikes',x:len-760,y:536,w:80,h:24});enemies.push({type:'elite',x:len-600,y:500,hp:3+difficulty,dir:-1,patrol:120})}return{n,act,biome,boss,len,parts,hazards,enemies,decor,goal:len-250,projectiles:[],checkpoints:[1150,len*.48],time:0}}
function start(n){save.stage=n;world=makeLevel(n);p={x:70,y:500,w:34,h:68,vx:0,vy:0,facing:1,onGround:false,jumps:2,coyote:0,wall:0,wallJump:0,hp:3+save.skills.health,maxHp:3+save.skills.health,inv:0,attack:0,combo:0,comboTimer:0,shuriken:0,dash:0,checkpoint:70};running=true;paused=false;panel.classList.add('hidden');menu.classList.add('hidden');hud.classList.remove('hidden');touch.classList.remove('hidden');updateHud()}
window.start=start;
function updateHud(){if(!p)return;document.getElementById('actLabel').textContent='ATO '+['I','II','III','IV'][Math.ceil(world.n/20)-1];document.getElementById('stageLabel').textContent='FASE '+world.n;document.getElementById('coinLabel').textContent='◈ '+save.coins;document.getElementById('hpLabel').textContent='♥'.repeat(Math.max(0,p.hp))}
function pause(){if(!running)return;paused=!paused;if(paused)panelShow(`<h2>PAUSA</h2><p class="story">${world.biome==='gelo'?'A prisão congelada':'A sombra'} aguarda. Respire e escolha seu próximo movimento.</p><button onclick="pause()">CONTINUAR</button><button onclick="quit()">SAIR DA FASE</button>`);else{panel.classList.add('hidden');hud.classList.remove('hidden');touch.classList.remove('hidden')}}window.quit=()=>{running=false;paused=false;panel.classList.add('hidden');menu.classList.remove('hidden');hud.classList.add('hidden');touch.classList.add('hidden')};
function rect(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y}function solidAt(x,y){let hit=null;for(const q of world.parts){const px=q.moving?q.x+Math.sin(world.time*1.5+q.phase)*q.range:q.x;if(x>px-4&&x<px+q.w+4&&y>=q.y-90&&y<=q.y+12)hit={...q,x:px}}return hit}
function fx(x,y,type,count=8){for(let i=0;i<count;i++)particles.push({x,y,vx:(Math.random()-.5)*150,vy:(Math.random()-.8)*170,life:.6+Math.random()*.6,type})}
function hurt(){if(p.inv>0)return;p.hp--;p.inv=.75+save.skills.armor*.2;shake=8;fx(p.x+17,p.y+35,'hit',10);if(p.hp<=0){p.hp=p.maxHp;p.x=p.checkpoint;p.y=350;p.vy=0;fx(p.x,p.y,'smoke',18)}updateHud()}
function melee(){if(p.attack>0)return;p.attack=.24;p.combo=(p.comboTimer>0?p.combo+1:1);p.comboTimer=.42;fx(p.x+p.facing*35,p.y+28,'slash',5);const range=74+p.combo*8;for(const e of world.enemies){if(e.hp>0&&Math.abs(e.x-p.x)<range&&Math.abs(e.y-p.y)<100){e.hp-=1+(p.combo>=3?1:0);e.hit=.18;if(e.hp<=0){save.coins+=e.type==='boss'?50:5;fx(e.x,e.y,'coin',e.type==='boss'?35:10);if(e.type==='boss')e.dead=true}}}}
function shoot(){if(p.shuriken>0)return;p.shuriken=.35;world.projectiles.push({x:p.x+p.facing*28,y:p.y+25,vx:p.facing*780,life:1.4,spin:0})}
function dash(){if(p.dash>0)return;p.dash=.72-Math.min(.22,save.skills.dash*.04);p.vx=p.facing*820;p.inv=.25;fx(p.x,p.y,'dash',16);if(save.artifacts.shadow)fx(p.x-p.facing*25,p.y+30,'shadow',8)}
function jump(){if(p.coyote>0||p.jumps>0){p.vy=-650;p.jumps--;p.coyote=0;fx(p.x+17,p.y+68,'jump',7);return}if(p.wall){p.vy=-620;p.vx=-p.wall*360;p.facing=-p.wall;p.wallJump=.2;fx(p.x+17,p.y+35,'jump',9)}}
function update(dt){if(!running||paused)return;dt=Math.min(dt,.025);world.time+=dt;p.inv=Math.max(0,p.inv-dt);p.attack=Math.max(0,p.attack-dt);p.shuriken=Math.max(0,p.shuriken-dt);p.dash=Math.max(0,p.dash-dt);p.comboTimer=Math.max(0,p.comboTimer-dt);p.coyote=Math.max(0,p.coyote-dt);if(input.dash){dash();input.dash=false}if(input.attack){melee();input.attack=false}if(input.shuriken){shoot();input.shuriken=false}if(input.jump){jump();input.jump=false}let dir=(input.right?1:0)-(input.left?1:0);if(dir){p.facing=dir;p.vx+=(p.wallJump>0?dir*500:dir*310)*dt;p.vx=Math.max(-260,Math.min(260,p.vx))}else p.vx*=Math.pow(.0004,dt);p.wall=0;const side=solidAt(p.x+(dir||p.facing)*26,p.y+35);if(side&&!p.onGround&&p.vy>80){p.wall=dir||p.facing;p.vy=Math.min(p.vy,115)}p.wallJump=Math.max(0,p.wallJump-dt);p.vy+=1700*dt;let prevY=p.y;p.x+=p.vx*dt;p.y+=p.vy*dt;p.onGround=false;for(const q0 of world.parts){const q=q0.moving?{...q0,x:q0.x+Math.sin(world.time*1.5+q0.phase)*q0.range}:q0;if(p.x+p.w>q.x&&p.x<q.x+q.w&&prevY+p.h<=q.y&&p.y+p.h>=q.y&&p.vy>=0){p.y=q.y-p.h;p.vy=0;p.onGround=true;p.jumps=2;p.coyote=.1}}if(p.x<0)p.x=0;if(p.y>820){hurt();p.x=p.checkpoint;p.y=300;p.vy=0}for(const h of world.hazards){let hx=h.x,hy=h.y;if(h.type==='saw'){hx+=Math.sin(world.time*2+h.phase)*22;hy+=Math.cos(world.time*2+h.phase)*4}if(rect(p,{x:hx,y:hy,w:h.w,h:h.h}))hurt()}for(const e of world.enemies){if(e.dead)continue;e.hit=Math.max(0,(e.hit||0)-dt);if(e.type==='boss'){e.x+=Math.sin(world.time*.9)*65*dt;if(Math.abs(p.x-e.x)<100&&Math.random()<dt*1.5)hurt();if(Math.random()<dt*.7)world.projectiles.push({x:e.x,y:e.y+25,vx:(p.x<e.x?-1:1)*360,life:2,enemy:true})}else{e.x+=e.dir*(e.type==='ranged'?35:50)*dt;if(Math.abs(e.x-(e.home??e.x))>e.patrol)e.dir*=-1;e.home??=e.x;if(e.type==='ranged'&&Math.random()<dt*.35)world.projectiles.push({x:e.x,y:e.y+20,vx:(p.x<e.x?-1:1)*300,life:2,enemy:true});if(rect(p,{x:e.x,y:e.y,w:34,h:55}))hurt()}}
for(const q of world.projectiles){q.x+=q.vx*dt;q.life-=dt;q.spin+=dt*15;if(q.enemy&&rect(p,{x:q.x,y:q.y,w:18,h:8}))hurt();if(!q.enemy){for(const e of world.enemies){if(!e.dead&&Math.abs(q.x-e.x)<38&&Math.abs(q.y-e.y)<60){e.hp-=1+save.skills.shuriken;if(e.hp<=0){e.dead=true;save.coins+=5;fx(e.x,e.y,'coin',10)}q.life=0}}}}world.projectiles=world.projectiles.filter(q=>q.life>0);if(p.x>p.checkpoint+950)p.checkpoint=p.x;if(p.x>world.goal)complete();if(save.romance&&Math.random()<dt*.9)fx(p.x+Math.random()*80,p.y-25,'heart',1);updateHud()}
function complete(){running=false;save.unlocked=Math.max(save.unlocked,Math.min(80,world.n+1));save.stage=Math.min(80,world.n+1);save.coins+=world.boss?75:25;if(save.artifacts.heart&&Math.random()<.35)p.hp=Math.min(p.maxHp,p.hp+1);persist();panelShow(`<h2>${world.boss?'CHEFE DERROTADO':'FASE CONCLUÍDA'}</h2><p class="story">${world.boss?'A arena caiu em silêncio. A sombra recuou.':'O caminho adiante se abre.'}</p><p style="text-align:center;font-size:34px">${save.romance?'♥ ✦ ♥ ✦ ♥':'✦ ✦ ✦'}</p><p class="story">Recompensa: <b>◈ ${world.boss?75:25}</b></p><button onclick="start(${Math.min(80,world.n+1)})">PRÓXIMA FASE</button><button onclick="stages()">MAPA DE FASES</button><button onclick="quit()">MENU</button>`)}
function draw(){ctx.clearRect(0,0,VW,VH);cam=Math.max(0,Math.min(world?world.len-VW:0,(p?.x||0)-420));const theme={gelo:['#06111a','#10283b','#4f7185','#b7d2de'],floresta:['#06110d','#0d2a1f','#2c5744','#8fb39b'],pantano:['#0b0d12','#25271c','#555a35','#9c9d62'],ruinas:['#100b12','#2b1d2b','#624457','#c1a1ae'],fortaleza:['#07080e','#161b29','#353c51','#9da7bb']}[world?.biome||'gelo'];ctx.fillStyle=theme[0];ctx.fillRect(0,0,VW,VH);parallax(theme);if(world){for(const q0 of world.parts){const q=q0.moving?{...q0,x:q0.x+Math.sin(world.time*1.5+q0.phase)*q0.range}:q0;drawPlatform(q,theme)}for(const d of world.decor)drawDecor(d,theme);for(const h of world.hazards)drawHazard(h,theme);for(const e of world.enemies)if(!e.dead)drawEnemy(e,theme);for(const q of world.projectiles)drawProjectile(q);drawPlayer(theme);drawParticles();if(world.boss){const boss=world.enemies.find(e=>e.type==='boss');if(boss&&!boss.dead){ctx.fillStyle='rgba(0,0,0,.55)';ctx.fillRect(VW/2-190,20,380,8);ctx.fillStyle='#d05a6c';ctx.fillRect(VW/2-190,20,380*Math.max(0,boss.hp/boss.maxHp),8)}}}if(shake>0){shake*=.82}}
function parallax(t){for(let layer=0;layer<3;layer++){ctx.fillStyle=t[layer+1];for(let i=0;i<14;i++){let x=((i*170-cam*(.08+layer*.06))%2380+2380)%2380;let h=90+((i*43+layer*51)%170);ctx.beginPath();ctx.moveTo(x,610);ctx.lineTo(x+70,610-h);ctx.lineTo(x+150,610);ctx.fill()} }ctx.globalAlpha=.22;ctx.fillStyle='#fff';for(let i=0;i<60;i++){let x=((i*233-cam*.03)%1280+1280)%1280,y=(i*79)%520;ctx.fillRect(x,y,1,1)}ctx.globalAlpha=1}
function drawPlatform(q,t){ctx.fillStyle=t[3];ctx.fillRect(q.x-cam,q.y,q.w,q.h);ctx.fillStyle='rgba(0,0,0,.35)';ctx.fillRect(q.x-cam,q.y,q.w,8);ctx.fillStyle='rgba(255,255,255,.08)';ctx.fillRect(q.x-cam,q.y+8,q.w,2)}
function drawHazard(h,t){let x=h.x-cam,y=h.y;if(h.type==='spikes'){ctx.fillStyle='#c55a67';for(let i=0;i<h.w;i+=14){ctx.beginPath();ctx.moveTo(x+i,y+24);ctx.lineTo(x+i+7,y);ctx.lineTo(x+i+14,y+24);ctx.fill()}}else{let cx=x+h.w/2,cy=y+h.h/2;ctx.save();ctx.translate(cx,cy);ctx.rotate(world.time*3+h.phase);ctx.fillStyle='#b9c1ca';for(let i=0;i<10;i++){ctx.rotate(Math.PI/5);ctx.fillRect(-3,-19,6,38)}ctx.beginPath();ctx.arc(0,0,12,0,Math.PI*2);ctx.fillStyle='#222a34';ctx.fill();ctx.restore()}}
function drawDecor(d,t){let x=d.x-cam;ctx.fillStyle='#18212c';ctx.fillRect(x, d.y, 5,70);ctx.fillStyle='#d9a65e';ctx.beginPath();ctx.arc(x+2,d.y,10,0,Math.PI*2);ctx.fill();ctx.globalAlpha=.08;ctx.fillStyle='#ffcf7a';ctx.beginPath();ctx.arc(x+2,d.y,38,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1}
function drawEnemy(e,t){ctx.save();ctx.translate(e.x-cam,e.y);ctx.globalAlpha=e.hit>0?.5:1;ctx.fillStyle=e.type==='boss'?'#5e2637':e.type==='elite'?'#2b3140':'#10151c';ctx.beginPath();ctx.arc(17,16,e.type==='boss'?30:17,0,Math.PI*2);ctx.fill();ctx.fillRect(3,29,28,e.type==='boss'?65:40);ctx.fillStyle='#dbe6ed';ctx.fillRect(9,12,7,3);ctx.fillStyle='#7d93a7';ctx.fillRect(29,36,25,4);ctx.restore()}
function drawProjectile(q){ctx.save();ctx.translate(q.x-cam,q.y);ctx.rotate(q.spin||0);ctx.fillStyle=q.enemy?'#d65c68':'#e9f0f4';ctx.fillRect(-9,-2,18,4);ctx.restore()}
function drawPlayer(t){if(!p)return;ctx.save();ctx.translate(p.x-cam,p.y);ctx.scale(p.facing,1);ctx.globalAlpha=p.inv>0&&Math.floor(p.inv*18)%2?.35:1;ctx.fillStyle='#05080d';ctx.beginPath();ctx.arc(17,16,17,0,Math.PI*2);ctx.fill();ctx.fillRect(4,30,27,38);ctx.fillStyle='#dce7ef';ctx.fillRect(17,13,9,3);ctx.fillStyle='#0d131b';ctx.fillRect(-7,33,12,9);ctx.fillRect(28,33,12,9);if(p.attack>0){ctx.strokeStyle='#e8f0f5';ctx.lineWidth=5;ctx.beginPath();ctx.arc(26,34,42,-.75,.65);ctx.stroke()}ctx.restore()}
function drawParticles(){for(const a of particles){ctx.globalAlpha=Math.max(0,a.life);ctx.fillStyle=a.type==='heart'?'#f16f95':a.type==='coin'?'#e7c15d':a.type==='hit'?'#d36a73':'#dce8f0';if(a.type==='heart'){ctx.font='18px serif';ctx.fillText('♥',a.x-cam,a.y)}else{ctx.fillRect(a.x-cam,a.y,5,5)}ctx.globalAlpha=1;a.x+=a.vx*.016;a.y+=a.vy*.016;a.vy+=90*.016;a.life-=.016}particles=particles.filter(a=>a.life>0)}
function loop(t){const dt=(t-last)/1000;last=t;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
